In [28]:
#%display plain
%display latex

In [2]:
from matplotlib import cm
import numpy as np
import itertools
from itertools import combinations
from __future__ import print_function

In [3]:
real_vars = var('r,t,theta,phi,x,y,z')
for rv in real_vars:
    assume(rv, 'real')
    
    
xs = var(['x{}'.format(n) for n in range(5)])
for xi in xs: assume(xi,'real')

ys = var(['y{}'.format(n) for n in range(4)])
for yi in ys: assume(yi,'real')
    
    
p1 = sum([xi   for xi in xs])
p2 = sum([xi^2 for xi in xs])
p3 = sum([xi^3 for xi in xs])
p4 = sum([xi^4 for xi in xs])
p5 = sum([xi^5 for xi in xs])

    
e1 = sum([ xi             for (xi,           ) in combinations(xs,1)])
e2 = sum([ xi*xj          for (xi,xj         ) in combinations(xs,2)])
e3 = sum([ xi*xj*xk       for (xi,xj,xk      ) in combinations(xs,3)])
e4 = sum([ xi*xj*xk*xl    for (xi,xj,xk,xl   ) in combinations(xs,4)])    
e5 = sum([ xi*xj*xk*xl*xm for (xi,xj,xk,xl,xm) in combinations(xs,5)])

In [4]:
com = vector([1,1,1,1,1])/sqrt(5) # center of mass

j1 = vector(QQ,[1,0,0,0,0])
j2 = vector(QQ,[0,1,0,0,0])
j3 = vector(QQ,[0,0,1,0,0])
j4 = vector(QQ,[0,0,0,1,0])

j1 = j1 - (j1*com)*com/com.norm()^2
j2 = j2 - (j2*com)*com/com.norm()^2
j3 = j3 - (j3*com)*com/com.norm()^2
j4 = j4 - (j4*com)*com/com.norm()^2

j2 = j2 - (j2*j1)*j1/j1.norm()^2
j3 = j3 - (j3*j1)*j1/j1.norm()^2
j4 = j4 - (j4*j1)*j1/j1.norm()^2

j3 = j3 - (j3*j2)*j2/j2.norm()^2
j4 = j4 - (j4*j2)*j2/j2.norm()^2

j4 = j4 - (j4*j3)*j3/j3.norm()^2

j1 = j1/j1.norm()
j2 = j2/j2.norm()
j3 = j3/j3.norm()
j4 = j4/j4.norm()

matrix([j1, j2, j3, j4]).transpose() # display as column vecs

[   2*sqrt(1/5)              0              0              0]
[-1/2*sqrt(1/5)    1/2*sqrt(3)              0              0]
[-1/2*sqrt(1/5)   -1/6*sqrt(3)      sqrt(2/3)              0]
[-1/2*sqrt(1/5)   -1/6*sqrt(3) -1/2*sqrt(2/3)      sqrt(1/2)]
[-1/2*sqrt(1/5)   -1/6*sqrt(3) -1/2*sqrt(2/3)     -sqrt(1/2)]

In [5]:
Pm = matrix([com,j1,j2,j3,j4]).transpose()

Pl = matrix([j1,j2,j3,j4]).transpose()

Qm = matrix([[0,0,0,0],
             [1,0,0,0],
             [0,1,0,0],
             [0,0,1,0],
             [0,0,0,1]])

In [6]:
# the (5 choose 3) 3-body interations in 4 dimensions
three_coincidences = [ matrix([[1, 1, 1, 1, 1],
                               [1,-1, 0, 0, 0],
                               [0, 1,-1, 0, 0]]),
                       matrix([[1, 1, 1, 1, 1],
                               [1,-1, 0, 0, 0],
                               [0, 1, 0,-1, 0]]),
                       matrix([[1, 1, 1, 1, 1],
                               [1,-1, 0, 0, 0],
                               [0, 1, 0, 0,-1]]),
                       matrix([[1, 1, 1, 1, 1],
                               [1, 0,-1, 0, 0],
                               [0, 0, 1,-1, 0]]),
                       matrix([[1, 1, 1, 1, 1],
                               [1, 0,-1, 0, 0],
                               [0, 0, 1, 0,-1]]),
                       matrix([[1, 1, 1, 1, 1],
                               [1, 0, 0,-1, 0],
                               [0, 0, 0, 1,-1]]),
                       matrix([[1, 1, 1, 1, 1],
                               [0, 1,-1, 0, 0],
                               [0, 0, 1,-1, 0]]),
                       matrix([[1, 1, 1, 1, 1],
                               [0, 1,-1, 0, 0],
                               [0, 0, 1, 0,-1]]),
                       matrix([[1, 1, 1, 1, 1],
                               [0, 1, 0,-1, 0],
                               [0, 0, 0, 1,-1]]),
                       matrix([[1, 1, 1, 1, 1],
                               [0, 0, 1,-1, 0],
                               [0, 0, 0, 1,-1]]) ]

three_body_4d = [ (M*Pl).right_kernel().basis_matrix() for M in three_coincidences ]
three_body_4d = [ (M[0]/M[0].norm(),M[1]/M[1].norm()) for M in three_body_4d ]

# the (5 choose 4) 4-body interations in 4 dimensions
four_coincidences = [ matrix([[ 1, 1, 1, 1, 1],
                              [ 1,-1, 0, 0, 0],
                              [ 0, 1,-1, 0, 0],
                              [ 0, 0, 1,-1, 0]]),
                      matrix([[ 1, 1, 1, 1, 1],
                              [ 1,-1, 0, 0, 0],
                              [ 0, 1,-1, 0, 0],
                              [ 0, 0, 1, 0,-1]]),
                      matrix([[ 1, 1, 1, 1, 1],
                              [ 1,-1, 0, 0, 0],
                              [ 0, 1, 0,-1, 0],
                              [ 0, 0, 0, 1,-1]]),
                      matrix([[ 1, 1, 1, 1, 1],
                              [ 1, 0,-1, 0, 0],
                              [ 0, 0, 1,-1, 0],
                              [ 0, 0, 0, 1,-1]]),
                      matrix([[ 1, 1, 1, 1, 1],
                              [ 0, 1,-1, 0, 0],
                              [ 0, 0, 1,-1, 0],
                              [ 0, 0, 0, 1,-1]]) ]

four_body_4d = [ (M*Pl).right_kernel().basis_matrix()[0] for M in four_coincidences ]
four_body_4d = [ (v/v.norm()).simplify_full() for v in four_body_4d ]

In [7]:
# the (5 choose 3) 3-body interations in 5 dimensions 
# (there is another dimension for each, in the "total coincidence" direction)

three_body_5d = [ M.right_kernel().basis_matrix() for M in three_coincidences ]
three_body_5d = [ ((M[0]/M[0].norm()).simplify_full(),(M[1]/M[1].norm()).simplify_full()) for M in three_body_5d ]

four_body_5d = [ M.right_kernel().basis_matrix()[0] for M in four_coincidences ]
four_body_5d = [ (v/v.norm()).simplify_full() for v in four_body_5d ]

In [8]:
f1 = e1(*(Pm*Qm*vector(ys))).simplify_full().expand()
f2 = e2(*(Pm*Qm*vector(ys))).simplify_full().expand()
f3 = e3(*(Pm*Qm*vector(ys))).simplify_full().expand()
f4 = e4(*(Pm*Qm*vector(ys))).simplify_full().expand()
f5 = e5(*(Pm*Qm*vector(ys))).simplify_full().expand()

pretty_print(f1)
pretty_print(f2)
pretty_print(f3)
pretty_print(f4)
pretty_print(f5)

0

-1/2*y0^2 - 1/2*y1^2 - 1/2*y2^2 - 1/2*y3^2

1/18*sqrt(3)*sqrt(2)*y2^3 - 1/6*sqrt(3)*sqrt(2)*y2*y3^2 + 1/10*sqrt(5)*y0^3 - 1/10*sqrt(5)*y0*y1^2 + 1/9*sqrt(3)*y1^3 - 1/10*sqrt(5)*y0*y2^2 - 1/6*sqrt(3)*y1*y2^2 - 1/10*sqrt(5)*y0*y3^2 - 1/6*sqrt(3)*y1*y3^2

1/60*sqrt(5)*sqrt(3)*sqrt(2)*y0*y2^3 - 1/20*sqrt(5)*sqrt(3)*sqrt(2)*y0*y2*y3^2 + 1/30*sqrt(5)*sqrt(3)*y0*y1^3 - 1/20*sqrt(5)*sqrt(3)*y0*y1*y2^2 - 1/20*sqrt(5)*sqrt(3)*y0*y1*y3^2 + 1/12*sqrt(2)*y1*y2^3 - 1/4*sqrt(2)*y1*y2*y3^2 - 3/80*y0^4 + 7/40*y0^2*y1^2 - 1/48*y1^4 + 7/40*y0^2*y2^2 + 1/8*y1^2*y2^2 + 7/40*y0^2*y3^2 + 1/8*y1^2*y3^2

-1/90*sqrt(3)*sqrt(2)*y0^2*y2^3 + 1/30*sqrt(5)*sqrt(2)*y0*y1*y2^3 + 1/30*sqrt(3)*sqrt(2)*y0^2*y2*y3^2 - 1/10*sqrt(5)*sqrt(2)*y0*y1*y2*y3^2 + 1/1000*sqrt(5)*y0^5 - 1/100*sqrt(5)*y0^3*y1^2 - 1/45*sqrt(3)*y0^2*y1^3 - 1/120*sqrt(5)*y0*y1^4 - 1/100*sqrt(5)*y0^3*y2^2 + 1/30*sqrt(3)*y0^2*y1*y2^2 + 1/20*sqrt(5)*y0*y1^2*y2^2 - 1/100*sqrt(5)*y0^3*y3^2 + 1/30*sqrt(3)*y0^2*y1*y3^2 + 1/20*sqrt(5)*y0*y1^2*y3^2

In [ ]:
def kelvin_transform(f, vrs):
    vr_vec = vector(vrs)
    sphere_inverted = vr_vec/vr_vec.norm()**2
    return f(**dict(zip(map(str,vrs),sphere_inverted)))*vr_vec.norm()**(2-len(vrs))

In [87]:
def symmetrize(f, vrs):
    if len(vrs) <= 1:
        return f
    other_vrs = vrs[1:]
    sym_f = f
    for vr in other_vrs:
        perm = dict(zip(map(str,vrs),vrs))
        perm[str(vrs[0])] = vr
        perm[str(vr)] = vrs[0]
        sym_f += f(**perm)
    return f/len(vrs)

In [173]:
def fourier_trans(f, degree):
    return vector([integrate(f*cos(t*n)/(2*pi), (t,0,2*pi)) for n in range(-degree,degree+1)])

In [174]:
def multi_index_gen(n, degree):
    for multi_index in multi_index_gen_helper(n, degree, degree):
        yield multi_index

def multi_index_gen_helper(n, degree, max_degree):
    if degree == 0:
        yield (0,)*n
    elif degree < 0:
        pass
    elif n == 1:
        if 0 <= degree <= max_degree:
            yield (degree,)
        else:
            pass
    else:
        for idx1 in range(max_degree,(degree//n)-1,-1):
            for multi_idx in multi_index_gen_helper(n-1,degree-idx1,idx1):
                yield (idx1,) + multi_idx

In [175]:
tbc_a, tbc_b = three_body_4d[0]

tbc = cos(t)*vector(SR,tbc_a) + sin(t)*vector(SR,tbc_b)

In [177]:
n = 4
degree = 60

fts = []

for count, multi_index in enumerate(multi_index_gen(n, degree)):
    assert len(multi_index) == n and sum(multi_index) == degree and all([idx >=0 for idx in multi_index])

    har_fn = vector(ys).norm()**(2-n)
    for vr, idx in zip(ys, multi_index):
        har_fn = diff(har_fn, vr, idx)

    har_fn = kelvin_transform(har_fn, ys) #.simplify_full()    

    har_fn = symmetrize(har_fn, ys)
    
    #plot( har_fn(*tbc).simplify_trig().reduce_trig(), (t,0,2*pi)).show()
    fts.append(fourier_trans(har_fn(*tbc).simplify_trig().reduce_trig(), 60))
    print(count)
    
#har_fn

0


TypeError: ECL says: Console interrupt.